### ISSUE TITLE
Invalid README commands

### ISSUE THREAD

**Issue by Muhammedijas981** [alpaDrive/vehicle#9]
In the documentation, within the [**Setting up the software**](https://github.com/alpaDrive/vehicle#setting-up-the-software) section, there is a command for checking the Python imports. This won't work as it's missing the `python3` command itself.

```bash
$ sudo __tests__/check.py # again run as root
# change it to 
$ sudo python3 __tests__/check.py
```

Moreover, I have spotted that all bash commands in the docs are preceded by the `$` symbol to indicate they're not being run as root. While informative, this compromises ease of use for newcomers. The commands by themselves would be easier to copy paste into a terminal.

**Comment by vishalkrishnads** [comment]
Oops! Noted. Also, I have noticed a rogue error in the `check.py` script 😑. I really don't know how we missed this in v0.1. Anyway, we'll use this opportunity to fix both.

Right now, `check.py` is

```python
try:
    import obd, pynmea2, qrcode, pyserial, requests, websockets, qrcode # notice here
    print("You're good to go! All modules have been installed and appear to be working fine...")
except Exception as e:
    print("Some modules couldn't be imported. This is what the Python interpreter has to say...\n")
    # ... rest of the code
```

Actually, `pyserial` is imported as `serial`. This is correctly done in the production code but the test script always crashes. This has to be changed.
